environment: dev
nifi_url: "https://127.0.0.1:8443"
nifi_username: "admin"
nifi_registry_url: "http://127.0.0.1:18080"
nifi_registry_internal_url: "http://172.31.20.146:18080"
aws_region: eu-west-2
aws_secrets_prefix: "openflow/dev"
snowflake_account: "cngfczx-ow26289"

flows:
  - name: "Salesforce Ingestion"
    flow_file: "../nifi/flows/salesforce_ingestion.json"
    parameter_context_file: "../nifi/parameter_contexts/dev.json"
    registry_bucket: "openflow-flows"
    process_group_name: "Salesforce Ingestion [dev]"

  - name: "PostgreSQL CDC"
    flow_file: "../nifi/flows/postgres_cdc.json"
    parameter_context_file: "../nifi/parameter_contexts/dev.json"
    registry_bucket: "openflow-flows"
    process_group_name: "PostgreSQL CDC [dev]"
