-- Run once per environment. Replace OPENFLOW_DEV with OPENFLOW_TEST / OPENFLOW_PROD as appropriate.
-- Snowflake account: cngfczx-ow26289 (AWS eu-west-2)

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS OPENFLOW_DEV   DATA_RETENTION_TIME_IN_DAYS = 1  COMMENT = 'OpenFlow dev environment';
CREATE DATABASE IF NOT EXISTS OPENFLOW_TEST  DATA_RETENTION_TIME_IN_DAYS = 7  COMMENT = 'OpenFlow test environment';
CREATE DATABASE IF NOT EXISTS OPENFLOW_PROD  DATA_RETENTION_TIME_IN_DAYS = 90 COMMENT = 'OpenFlow production environment';

-- Warehouses
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_INGEST_WH_DEV
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'NiFi ingestion - dev';

CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_INGEST_WH_TEST
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'NiFi ingestion - test';

CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_INGEST_WH_PROD
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'NiFi ingestion - prod';
