-- Create schemas in each environment database.
-- Repeat for TEST and PROD by substituting the database name.

USE ROLE SYSADMIN;
USE DATABASE OPENFLOW_DEV;

-- Raw landing zone — NiFi writes here directly via COPY INTO
CREATE SCHEMA IF NOT EXISTS RAW
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = 'Raw landing zone from NiFi ingestion';

-- Salesforce source data
CREATE SCHEMA IF NOT EXISTS SALESFORCE
  DATA_RETENTION_TIME_IN_DAYS = 7
  COMMENT = 'Cleaned Salesforce objects';

-- PostgreSQL CDC data
CREATE SCHEMA IF NOT EXISTS POSTGRES_CDC
  DATA_RETENTION_TIME_IN_DAYS = 7
  COMMENT = 'CDC stream from RDS Postgres';

-- Repeat for TEST
USE DATABASE OPENFLOW_TEST;
CREATE SCHEMA IF NOT EXISTS RAW        DATA_RETENTION_TIME_IN_DAYS = 1;
CREATE SCHEMA IF NOT EXISTS SALESFORCE DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS POSTGRES_CDC DATA_RETENTION_TIME_IN_DAYS = 7;

-- Repeat for PROD
USE DATABASE OPENFLOW_PROD;
CREATE SCHEMA IF NOT EXISTS RAW        DATA_RETENTION_TIME_IN_DAYS = 1;
CREATE SCHEMA IF NOT EXISTS SALESFORCE DATA_RETENTION_TIME_IN_DAYS = 90;
CREATE SCHEMA IF NOT EXISTS POSTGRES_CDC DATA_RETENTION_TIME_IN_DAYS = 90;
