-- Roles and grants for OpenFlow service accounts.
-- Run as ACCOUNTADMIN (storage integration requires it).

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- Storage Integration (S3 → Snowflake, AWS eu-west-2)
-- ============================================================

CREATE STORAGE INTEGRATION IF NOT EXISTS OPENFLOW_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::866586366759:role/openflow-snowflake-s3-dev'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://openflow-staging-dev-eu-west-2/',
    's3://openflow-staging-test-eu-west-2/',
    's3://openflow-staging-prod-eu-west-2/'
  );

-- After running this, retrieve the Snowflake IAM values and update the AWS trust policy:
--   DESC INTEGRATION OPENFLOW_S3_INTEGRATION;
-- Copy STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID into the Terraform
-- aws_iam_role.snowflake_s3_access trust policy.

-- ============================================================
-- Service account roles
-- ============================================================

USE ROLE SYSADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_INGEST_ROLE COMMENT = 'NiFi ingestion service account';
CREATE ROLE IF NOT EXISTS OPENFLOW_READ_ROLE   COMMENT = 'Read-only access to OpenFlow data';

-- Ingest role grants (dev)
GRANT USAGE ON DATABASE OPENFLOW_DEV                          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE OPENFLOW_INGEST_WH_DEV               TO ROLE OPENFLOW_INGEST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_DEV           TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_DEV.RAW            TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_DEV.SALESFORCE     TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_DEV.POSTGRES_CDC   TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE OPENFLOW_DEV           TO ROLE OPENFLOW_INGEST_ROLE;
GRANT READ ON STAGE OPENFLOW_DEV.RAW.OPENFLOW_S3_STAGE        TO ROLE OPENFLOW_INGEST_ROLE;
GRANT WRITE ON STAGE OPENFLOW_DEV.RAW.OPENFLOW_S3_STAGE       TO ROLE OPENFLOW_INGEST_ROLE;

-- Mirror for TEST
GRANT USAGE ON DATABASE OPENFLOW_TEST                          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE OPENFLOW_INGEST_WH_TEST               TO ROLE OPENFLOW_INGEST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_TEST           TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_TEST.RAW          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_TEST.SALESFORCE   TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_TEST.POSTGRES_CDC TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE OPENFLOW_TEST           TO ROLE OPENFLOW_INGEST_ROLE;

-- Mirror for PROD
GRANT USAGE ON DATABASE OPENFLOW_PROD                          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE OPENFLOW_INGEST_WH_PROD               TO ROLE OPENFLOW_INGEST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_PROD           TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_PROD.RAW          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_PROD.SALESFORCE   TO ROLE OPENFLOW_INGEST_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA OPENFLOW_PROD.POSTGRES_CDC TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE OPENFLOW_PROD           TO ROLE OPENFLOW_INGEST_ROLE;

-- Read-only role (all envs)
GRANT USAGE ON DATABASE OPENFLOW_DEV   TO ROLE OPENFLOW_READ_ROLE;
GRANT USAGE ON DATABASE OPENFLOW_TEST  TO ROLE OPENFLOW_READ_ROLE;
GRANT USAGE ON DATABASE OPENFLOW_PROD  TO ROLE OPENFLOW_READ_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_DEV  TO ROLE OPENFLOW_READ_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_TEST TO ROLE OPENFLOW_READ_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_PROD TO ROLE OPENFLOW_READ_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE OPENFLOW_DEV  TO ROLE OPENFLOW_READ_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE OPENFLOW_TEST TO ROLE OPENFLOW_READ_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE OPENFLOW_PROD TO ROLE OPENFLOW_READ_ROLE;

-- Service account users
USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS OPENFLOW_NIFI_SVC
  DEFAULT_ROLE = OPENFLOW_INGEST_ROLE
  DEFAULT_WAREHOUSE = OPENFLOW_INGEST_WH_DEV
  COMMENT = 'NiFi service account';

GRANT ROLE OPENFLOW_INGEST_ROLE TO USER OPENFLOW_NIFI_SVC;
GRANT ROLE OPENFLOW_READ_ROLE   TO USER OPENFLOW_NIFI_SVC;

-- Future grants (ensures new tables/schemas are covered automatically)
USE ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_DEV.RAW          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_DEV.SALESFORCE   TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_DEV.POSTGRES_CDC TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_TEST.RAW          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_TEST.SALESFORCE   TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_TEST.POSTGRES_CDC TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_PROD.RAW          TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_PROD.SALESFORCE   TO ROLE OPENFLOW_INGEST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENFLOW_PROD.POSTGRES_CDC TO ROLE OPENFLOW_INGEST_ROLE;
